#!/opt/conda/bin/python3.8
# -*- coding: utf-8 -*-
import re
import sys
from lddl.dask.bert.pretrain_codebert import console_script

if __name__ == "__main__":
    sys.argv[0] = re.sub(r"(-script\.pyw|\.exe)?$", "", sys.argv[0])
    sys.exit(console_script())
